name: ragpdf
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - transformers
      - sentence-transformers
      - langchain
      - faiss-cpu
      - pypdf
